### ISSUE TITLE
FlowFuse login fails in fire-walled network

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/flowfuse#4503]
### Description

We have a customer who wants to be able to access FF Cloud from their partially locked-down network. When they try the login fails before the full FF interface is loaded. The same login works fine from client devices outside of the their network.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by robmarcer** [comment]
As requested @hardillb

**Comment by knolleary** [comment]
@hardillb do we believe this is resolved on FFC since the PH fixes?

**Comment by hardillb** [comment]
We haven't had a response from the customer yet (@robmarcer any update?)

But in local testing in as close an environment as possible I believe so.

**Comment by robmarcer** [comment]
I asked last week (just asked again as I think the question got lost in a an email thread). I assume it's resolved and happy to close this issue, if I get feedback that it's still an issue I will reopen.
